# This is a basic workflow to help you get started with Actions

name: Deploy Google Functions

# Controls when the workflow will run
"on":
  workflow_dispatch:
   inputs:
    environment:
     description: 'Environment'
     required: true
     default: 'fir-learning-a511d'
    project: 
     descripton: 'Project Name'
     required: true
     default: 'fir-learning-a511d'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest