# This is a basic workflow to help you get started with Actions

name: Deploy Google Functions

# Controls when the workflow will run
"on":
  workflow_dispatch:
   inputs:
    environment:
     description: 'Environment'
     required: true
     default: 'fir-learning-a511d'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     matrix: 
      node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/node@v1
        with: 
         node-version: ${{matrix.node-version}} 
      - name: install libraries firebase-learning
        if: github.event.inputs.environment == "firebase-learning"
        run: npm install
        working-directory: ./my_google_firebase_learning/functions
     - name: deploy firebase-learning
       uses: w9jds/firebase-action@master
       if: github.event.inputs.environment == "firebase-learning"
       with : 
         args: deploy --only functions:api
       env:
         GCP_SA_KEY: ${{secretes.FIREBASE_LEARNING_BASE64}}  
         PROJECT_PATH: ./my_google_firebase_learning
         PROJECT_ID: fir-learning-a511d

